### ISSUE TITLE
Repo license seemingly violated by 'Cruicial By Micron'

### ISSUE THREAD

**Issue by EliseZeroTwo** [QCute/WinRing0#2]
I was REing the MOD utility provided by Crucial for their products RGB management and they ship a signed version of this with it.

Here is a screenshot of the file titled `MODAPI.sys` from their MOD utility

![violation in IDA](https://user-images.githubusercontent.com/42453798/121781517-b3f97300-cb94-11eb-9163-15acb894d3e8.png)

**Comment by phx-veronica** [comment]
Nope, whoever uploaded this repo put the wrong license on it. The original license can be found here: https://github.com/xmrig/xmrig/blob/master/bin/WinRing0/LICENSE
